// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbzkwtyrthhmedrmbvmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtiemt3dHlydGhobWVkcm1idm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4ODc4OTgsImV4cCI6MjA1NDQ2Mzg5OH0.tAAfErT5IiuN3KCyQWlfmQ8PP49RwiLHgQ9WD4PEoOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);